# fly.toml app configuration file generated for jliocsar on 2023-11-24T18:17:22-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jliocsar"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
